AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  room-monitoring-api

  Sample SAM Template for room-monitoring-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 30
    Handler: app.handler
Parameters:
  AwsRoomMonitoringCognitoUserPoolId:
    Type: String
  AwsRoomMonitoringCognitoClientId:
    Type: String
  DynamoDBTableName:
    Type: String

Resources:

  CognitoAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy to allow access to cognito idp
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "cognito-idp:AdminInitiateAuth"
            Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${AwsRoomMonitoringCognitoUserPoolId}"
            Effect: Allow

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          RoomMonitoringAuthorizer:
            IdentitySource: $request.header.authorization
            JwtConfiguration:
              audience:
                - !Ref AwsRoomMonitoringCognitoClientId
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${AwsRoomMonitoringCognitoUserPoolId}"
        DefaultAuthorizer: RoomMonitoringAuthorizer
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
      DefinitionBody:
        info:
          version: "1.0"
          title: !Ref AWS::StackName
        paths: {}
        openapi: 3.0.1
      StageName: "v1"


  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    PackageType: Zip
    Properties:
      CodeUri: src/functions/auth/
      Events:
        PostAuth:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref HttpApi
            Path: /auth
            Method: POST
      Policies:
        - !Ref CognitoAdminPolicy
      Environment:
        Variables:
          COGNITO_CLIENT_ID: !Ref AwsRoomMonitoringCognitoClientId
          COGNITO_USER_POOL_ID: !Ref AwsRoomMonitoringCognitoUserPoolId
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - app.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: AuthFunction

  RegisterDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    PackageType: Zip
    Properties:
      CodeUri: src/functions/register-data/
      Events:
        PostRegisterData:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref HttpApi
            Path: /register
            Method: POST
            Auth:
              Authorizer: RoomMonitoringAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MonitoringRoomSingleTable
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - app.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: RegisterDataFunction

  MonitoringRoomSingleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: monitoring-room-single-table
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 

Outputs:
  RoomMonitoringApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/v1/"